"use client";

import "./globals.css";
import type { Metadata } from "next";
import { ThemeProvider } from "@/components/ThemeProvider";
import Header from "@/components/Header";
import SessionNextProvider from "@/components/SessionNextProvider";

export const metadata: Metadata = {
  title: "Aldi Ahmad Fahrizi Ilmawan | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <SessionNextProvider>
            {children}
            {/* <SocialMedia /> */}
          </SessionNextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
